name: Master Continuous Integration

on:
  push:
    branches: [Master, main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Code
        run: pytest -v

      - run: yarn install

      - name: Validate serverless.yml
        uses: serverless/github-action@master
        with:
          args: package --stage=master --verbose
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_MASTER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_MASTER }}
          SLS_DEBUG: 1
